### ISSUE TITLE
nitdoc: does not show the correct signature of the anonymous constructor

### ISSUE THREAD

**Issue by xymus** [privat/nit#1195] opened 2015-03-10 18:08 UTC
nitdoc always shows the anonymous "init" constructor as a having no arguments. It looks like it displays only information on its introduction in Object.

This is very impractical, since the constructors have gotten more complex it gets harder to guess the signature.

See the popular `Container[E]` class for an example. It's anonymous constructor takes an argument of type `E`, but the doc shows an empty signature.
http://nitlanguage.org/doc/stdlib/class_standard__collection__abstract_collection__Container.html#standard__kernel__Object__init

Assigned to @privat because he introduced the new constructors which (probably) broke nitdoc. I'm trying to fix the same issue in the Vim plugin and can't get anywhere, I can't get the usual resolve/anchor methods to do their black magic. I could use some sample code to reproduce!

**Comment by Morriar** [comment] 2015-03-10 18:58
Yeah, that assignee is just fine :)

**Comment by privat** [comment] 2015-03-11 02:01
I can do it, but what is the status of nitdoc in term of code-stability?

**Comment by privat** [comment] 2015-03-11 02:03
duplicate of #875 that is assigned to @Morriar since november :)

**Comment by xymus** [comment] 2015-04-11 16:47
@privat, if @Morriar doesn't take your offer to fix it in Nitdoc, you can fix it for the doc in Vim instead! :smile: 

Here's where I "print" the signature of all the properties of a class, you could add a condition for the anonymous constructor: https://github.com/privat/nit/blob/master/src/doc/vim_autocomplete.nit#L216

**Closed** 2015-05-20 11:02 UTC
Labels: bug, nitdoc
