### ISSUE TITLE
Document how to allocate and manage strings from foreign code

### ISSUE THREAD

**Issue by xymus** [privat/nit#1106] opened 2015-01-15 21:46 UTC

**Comment by R4PaSs** [comment] 2015-01-15 21:47
I'm expecting a storm of +1 for this issue, so yeah, alright I'll do it.

**Comment by ppepos** [comment] 2015-01-15 21:51
Boring

**Comment by Morriar** [comment] 2015-01-16 06:51
MFW i read that issue:

![image](https://cloud.githubusercontent.com/assets/583144/5772532/8149b7e6-9d54-11e4-9eaa-33aa28cf9c33.png)

**Comment by privat** [comment] 2015-01-16 10:29
duplicate of #69 ?

**Comment by xymus** [comment] 2015-01-16 19:16
I always considered #69 to concern _extern_ objects, as native object is a bit vague, but the example code did use strings. I would consider releasing strings to be a subissue of #69, but it is important enough to be assigned to our string specialist! There's also the need to clarify the API in relation to foreign code.

**Comment by R4PaSs** [comment] 2015-01-16 19:45
Actually, the example proposed by @Morriar is the perfect example of extern code leaking memory.

The `Int::to_s` implementation returns a `malloc`'d String, therefore it is never released by Boehm, a simple replacement of it by `nit_alloc` and collection proceeds as it should (there's actually only a few of these, one in `libevent` caught my attention as it might be one source of your Nitcorn troubles @xymus !).

Still, there are definitely some issues with FlatStrings. Especially when concatenating.

This example is resource leaking incarnated, no amount of `force_garbage_collection` changes the memory use of the program.

~~~nit
fun leak_cct do
    var s = ""
    for i in [0 .. 1000000] do s += "/"
end

leak_cct

force_garbage_collection

# Check memory use here
var t = gets
~~~

This is where the mystery itensifies, since NativeStrings are allocated with a `nit_alloc`, they should be released when memory gets low by Boehm's standards or when forcing a collection.

But they're not.

So, for foreign code (C-only, I suspect Obj-C and C++ to be similar, as for Java this will require further investigation), there are two choices:

* Either allocate strings as char* with a `nit_alloc` for them to be processed by Boehm
* Or use the copy-constructor in `NativeString`, `to_s_with_copy`, and release the char* in your Extern C code.

**Comment by xymus** [comment] 2015-01-16 20:01
Be careful with `force_garbage_collection` as it is more of a hint for the GC to try to free something, it may not do anything if there is no real need to free memory.

**Comment by xymus** [comment] 2015-01-16 20:27
OK, I didn't know the NativeString were allocated by the GC. With services like `to_s_with_copy` and pinning with `_incr_ref` we should have everything we need.

Still a few questions:

* If I am to send a malloc'd NativeString in the Nit system, use it with `Text::+` and free it later, can it be reused/leaked in a rope or something like that?

* What would be the correct way to implement `Int::to_s` instead of using a malloc? Allocate a NativeString from Nit, pass it to C to be filled and then wrap it in a String or FlatBuffer?

**Comment by R4PaSs** [comment] 2015-01-16 21:07
For your first question, I think we should refrain from doing things this way, indeed, some references might be kept in some place (due to the use of `+` or `substring` for instance), which will be invalidated when you free the `char*` leading to reading garbage and/or crashing farther in the program's execution, we don't want that.

I think that as a rule of thumb, we might say that every `char*` that is passed to Nit at any point should be made from a managed copy of the NativeString (like `to_s_with_copy` or `nit_alloc`'d `char*` with `to_s_with_length`)

As for `Int::to_s`, this very simple code does the job:

~~~C
#include "string_nit.h"
#include "nit.common.h"

char* native_int_to_s(long recv){
        int len = snprintf(NULL, 0, "%ld", recv);
        char* str = nit_alloc(len+1);
        sprintf(str, "%ld", recv);
        return str;
}
~~~

Another way of doing so, as you suggested, might be to allocate the `NativeString` on Nit's side and pass it to the method.

~~~C
#include "string_nit.h"

// str is supposed to have been pre-allocated by new NativeString
char* native_int_to_s(long recv, char* str){
        int len = snprintf(NULL, 0, "%ld", recv);
        sprintf(str, "%ld", recv);
        return str;
}
~~~

Though this would imply you know the size of the string to allocate prior to the call, which is not always the case (`native_int_to_s` being a good example for such a case).

**Comment by xymus** [comment] 2015-01-16 21:19
We do not expose `nit_alloc` to foreign code. It could be done, `ruby` does something similar but we can instead use normal callbacks to Nit methods, like to the `NativeString` constructor. I will probably use this in most of my code from now on.

For `Int::to_s` only, I would prefer the 2nd method. It uses the legacy NI so there's no callback et we know the size of the string.

So do you want to close this issue?

**Comment by R4PaSs** [comment] 2015-01-16 21:30
I'm all for the exposure of `nit_alloc` to extern methods !

For `NativeString` we can use the constructor too, I'd be happy with both alternatives (I actually like having several alternatives to a situation :) ).

As for Int::to_s, we don't know the size of the String to allocate prior to the call to native_int_to_s (`snprintf` is here to compute that) so it's one of those cases where allocation is best done inside the method I think.

And we can keep the issue open since there are still problems with the collection as shown by the concatenation example, when it's fixed we can close the issue !

**Comment by privat** [comment] 2015-03-19 06:38
Hum, the last part of the issue is still not done. "allocate them from foreign code." So I will rename the issue

**Comment by privat** [comment] 2015-07-14 19:59
closed by https://github.com/nitlang/nitlanguage/commit/deed73ccca4cbdcdded7130391a1b3b92bd69bd0

**Closed by privat** 2015-07-14 19:59 UTC
Labels: API
